// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_event from "./routes/api/event.ts";
import * as $api_timesheets_id_ from "./routes/api/timesheets/[id].ts";
import * as $api_timesheets_new_dateString_ from "./routes/api/timesheets/new/[dateString].ts";
import * as $api_user_dateString_ from "./routes/api/user/[dateString].ts";
import * as $api_user_handleLogin from "./routes/api/user/handleLogin.ts";
import * as $api_user_login from "./routes/api/user/login.ts";
import * as $api_user_logout from "./routes/api/user/logout.ts";
import * as $blog_index from "./routes/blog/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $timesheets_id_ from "./routes/timesheets/[id].tsx";
import * as $DatePicker from "./islands/DatePicker.tsx";
import * as $Sticky from "./islands/Sticky.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/event.ts": $api_event,
    "./routes/api/timesheets/[id].ts": $api_timesheets_id_,
    "./routes/api/timesheets/new/[dateString].ts":
      $api_timesheets_new_dateString_,
    "./routes/api/user/[dateString].ts": $api_user_dateString_,
    "./routes/api/user/handleLogin.ts": $api_user_handleLogin,
    "./routes/api/user/login.ts": $api_user_login,
    "./routes/api/user/logout.ts": $api_user_logout,
    "./routes/blog/index.tsx": $blog_index,
    "./routes/index.tsx": $index,
    "./routes/timesheets/[id].tsx": $timesheets_id_,
  },
  islands: {
    "./islands/DatePicker.tsx": $DatePicker,
    "./islands/Sticky.tsx": $Sticky,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
