// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/event.ts";
import * as $3 from "./routes/api/timesheet/[id].ts";
import * as $4 from "./routes/api/timesheet/new.ts";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/timesheets/[id].tsx";
import * as $7 from "./routes/timetracker/index.tsx";
import * as $$0 from "./islands/DatePicker.tsx";
import * as $$1 from "./islands/Sticky.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/event.ts": $2,
    "./routes/api/timesheet/[id].ts": $3,
    "./routes/api/timesheet/new.ts": $4,
    "./routes/index.tsx": $5,
    "./routes/timesheets/[id].tsx": $6,
    "./routes/timetracker/index.tsx": $7,
  },
  islands: {
    "./islands/DatePicker.tsx": $$0,
    "./islands/Sticky.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
